- hosts: localhost
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: target/MymavenWebApp01.war
        dest: /opt/tomcat/webapps/maven-webapp-final.war

