- hosts: localhost
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: target/MymavenWebapp01.war
        dest: /opt/tomcat/webapps/MymavenWebApp01-final.war

